# Generated by Django 5.1 on 2024-08-07 21:38

# Django Stuff
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("guid", models.UUIDField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("reference", models.CharField(max_length=100)),
                ("modified", models.DateTimeField()),
            ],
            options={
                "unique_together": {("guid", "reference")},
            },
        ),
    ]
