# Generated by Django 5.1 on 2024-08-07 22:41

# Django Stuff
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pilotlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aircraft",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="aircraft_class",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="complex",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="engine_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="equipment_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="gear_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="high_performance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="pressurized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="taa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="type_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="year",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="guid",
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="make",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.UUIDField(unique=True)),
                ("user_id", models.IntegerField()),
                ("date_utc", models.DateField()),
                ("date_base", models.DateField()),
                ("date_local", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                ("modified", models.DateTimeField()),
                ("from_airport", models.CharField(blank=True, max_length=100)),
                ("to_airport", models.CharField(blank=True, max_length=100)),
                ("route", models.TextField(blank=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("time_off", models.TimeField(blank=True, null=True)),
                ("time_on", models.TimeField(blank=True, null=True)),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("on_duty", models.TimeField(blank=True, null=True)),
                ("off_duty", models.TimeField(blank=True, null=True)),
                (
                    "total_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pic",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sic",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "solo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "cross_country",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nvg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nvg_ops",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("distance", models.IntegerField(blank=True, null=True)),
                ("day_takeoffs", models.IntegerField(blank=True, null=True)),
                ("day_landings_full_stop", models.IntegerField(blank=True, null=True)),
                ("night_takeoffs", models.IntegerField(blank=True, null=True)),
                (
                    "night_landings_full_stop",
                    models.IntegerField(blank=True, null=True),
                ),
                ("all_landings", models.IntegerField(blank=True, null=True)),
                (
                    "actual_instrument",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "simulated_instrument",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hobbs_start",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hobbs_end",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tach_start",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tach_end",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("holds", models.IntegerField(blank=True, null=True)),
                ("approach1", models.CharField(blank=True, max_length=100)),
                ("approach2", models.CharField(blank=True, max_length=100)),
                ("approach3", models.CharField(blank=True, max_length=100)),
                ("approach4", models.CharField(blank=True, max_length=100)),
                ("approach5", models.CharField(blank=True, max_length=100)),
                ("approach6", models.CharField(blank=True, max_length=100)),
                (
                    "dual_given",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dual_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "simulated_flight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ground_training",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("instructor_name", models.CharField(blank=True, max_length=100)),
                ("instructor_comments", models.TextField(blank=True)),
                ("person1", models.CharField(blank=True, max_length=100)),
                ("person2", models.CharField(blank=True, max_length=100)),
                ("person3", models.CharField(blank=True, max_length=100)),
                ("person4", models.CharField(blank=True, max_length=100)),
                ("person5", models.CharField(blank=True, max_length=100)),
                ("person6", models.CharField(blank=True, max_length=100)),
                ("flight_review", models.BooleanField(default=False)),
                ("checkride", models.BooleanField(default=False)),
                ("ipc", models.BooleanField(default=False)),
                ("nvg_proficiency", models.BooleanField(default=False)),
                ("faa6158", models.BooleanField(default=False)),
                ("custom_text", models.TextField(blank=True)),
                (
                    "custom_numeric",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "custom_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("custom_counter", models.IntegerField(blank=True, null=True)),
                ("custom_date", models.DateField(blank=True, null=True)),
                ("custom_datetime", models.DateTimeField(blank=True, null=True)),
                ("custom_toggle", models.BooleanField(default=False)),
                ("pilot_comments", models.TextField(blank=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pilotlog.aircraft",
                    ),
                ),
            ],
        ),
    ]
