target-version = "py310"

[tool.black]
target-version = ["py310"]
line-length = 88

[tool.ruff]
select = ["E", "F"]
ignore = ["E501", "E741"]

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
